name: First Workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some Text
        run: echo "Some Text"
      - name: Command in Multiline
        run: |
          node -v

          npm -v

          cat /etc/os-release

          cat /etc/hostname
          
          cat /etc/hosts